import '@styles/globals.scss'
import type { AppProps } from 'next/app'
import Header from '@src/components/Header'
import Head from 'next/head'
import { useHeadProps } from '@src/hooks/useHeadProps'

function MyApp({ Component, pageProps }: AppProps) {
	const headProps = useHeadProps()

	return (
		<>
			<Head>
				<title>{headProps.title}</title>
				<meta name={headProps.metaName} content='Generated by CKRAC' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<main>
				<Component {...pageProps} />
			</main>
		</>
	)
}

export default MyApp
