import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Ken And Rebecca Wedding</title>
				<meta name='description' content='Generated by CKRAC' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>Hello World</main>
		</div>
	)
}

export default Home
