myNextApplication:
  component: '@sls-next/serverless-component@latest'
  inputs:
    cloudfront:
      distributionId: ${env.DISTRIBUTION}
    bucketName: 'kennethrebecca.com'
    bucketRegion: ${env.AWS_REGION}
    build: true
