name: Deploy

on:
  push:
    branches: [ static-release ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      id-token: write    
    defaults:
      run:
        working-directory: ./apps/wedding    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.PROD_DEPLOY_REGION }}
      - run: aws s3 sync ./out s3://kennethrebecca.com